### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module not supported.

### ISSUE THREAD

**Issue by netandreus** [vlad-yakovlev/telegram-md#142]
### Error
After run this code
```
import { md } from '@vlad-yakovlev/telegram-md'
...
let markupResponse = md.build("Test");
...
```

I received errors:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/andrey/sandbox/test/current/node_modules/@vlad-yakovlev/telegram-md/dist/index.js from /Users/andrey/sandbox/test/current/backend/src/modules/application.module.ts not supported.
Instead change the require of index.js in /Users/andrey/sandbox/test/current/backend/src/modules/application.module.ts to a dynamic import() which is available in all CommonJS modules.
    at require.extensions..jsx.require.extensions..js (/private/var/folders/f9/1b1jz83s4ysfn9zfncbsb8y40000gn/T/ts-node-dev-hook-9053394042309917.js:114:20)
    at Object.nodeDevHook [as .js] (/Users/andrey/sandbox/test/current/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/Users/andrey/sandbox/test/current/backend/src/modules/application.module.ts:23:23)
    at Module._compile (/Users/andrey/sandbox/test/current/node_modules/source-map-support/source-map-support.js:568:25)
```

### Version

- "grammy": "1.20.3",
- "@vlad-yakovlev/telegram-md": "^2.0.0",
- "@vlad-yakovlev/grammy-reply-with-markdown": "^2.0.1"

**Comment by vlad-yakovlev** [comment]
Hey @netandreus, you see this error because you're trying to use ESM package in CommonJS environment. To solve this, I recommend you switch your environment to ESM by adding `"type": "module"` to your `package.json`. Alternatively you can try to use dynamic imports.
